baseURL: 'http://example.org/landing-pages'
languageCode: 'ja-JP'
theme: ['generic-dx', 'AndGo']
title: 'アンダーズ株式会社 | Generic DX'

# [Configure Modules | Hugo](https://gohugo.io/hugo-modules/configuration/)
module:
  hugoVersion:
    extended: true
    min: "0.100"
  mounts:
  - source: static
    target: static
  - source: uploads
    target: static

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  images:
    contactIcon: "images/envelope.png"
    logo: "images/mark_2w.png"
    president: "images/president.png"
    logoLine: "images/mark_3k.png"
  smtpjs:
    secureToken: 22152f6c-a021-4af1-90d4-cd093adb07c0 # dev,localhost
    fromMail: "contact@andaze.com"
    bccMail: "nishidai@andaze.com,contact-us@andaze.com,contact-us@andaze.com,d@solutus.jp"
    subject: "お問い合わせいただきありがとうございます。"
    confirmMessage:
      alert: "お問い合わせいただきありがとうざいます。"
      bodyHeader: "お問い合わせいただきありがとうざいます。"
      bodyFooter: "上記の内容にてお問い合わせを受け付けました。<br/>追って担当者から回答させていただきます。"
