---
# https://towardsdev.com/update-submodule-automatically-with-github-actions-repository-dispatch-event-8e548ab1f517
name: Send repository_dispatch event to parent repo  
  
on:  
  push:  
    branches:  
      - 'main'  
  
jobs:  
  notify-parent-repo:  
    runs-on: ubuntu-latest  
    steps:
      - name: Repository Dispatch  
        uses: peter-evans/repository-dispatch@v2 
        with:  
          token: ${{ secrets.DISPATCH_TOKEN_FOR_WEBCORPORATE_NEW }} # Set it up at https://github.com/organizations/andaze/settings/secrets/actions (get authorization)
          repository: andaze/WebCorporate
          event-type: sync-shared-submodules
          client-payload: '{"submodule": "${{ github.repository }}"}'