---
# https://towardsdev.com/update-submodule-automatically-with-github-actions-repository-dispatch-event-8e548ab1f517
name: Send repository_dispatch event to parent repo  
  
on:  
  push:  
    branches:  
      - '**'  
  
jobs:  
  notify-parent-repo:  
    runs-on: ubuntu-latest  
    steps:
      - name: Repository Dispatch  
        uses: peter-evans/repository-dispatch@v2 
        with:  
          # token: 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
          # token: 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
          repository: andaze/WebCorporate
          event-type: sync-shared-submodule