---
# https://towardsdev.com/update-submodule-automatically-with-github-actions-repository-dispatch-event-8e548ab1f517
name: Send repository_dispatch event to parent repo  
  
on:  
  push:  
    branches:  
      - '**'  
  
jobs:  
  notify-parent-repo:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Repository Dispatch  
        uses: peter-evans/repository-dispatch@v2  
        with:  
          token: ${{ secrets.REPOSITORY_DISPATCH }}
          repository: andaze/WebCorporate
          event-type: sync-shared-submodule